insert into position_composes_participates values
(6, 'Point Guard', 'Often lead their team in assists and steals. They are often quick and are able to hit shots either outside the three-point line or in the paint', 49),
(6, 'Shooting Guard', 'Often referred to as a wing because of its use in common positioning tactics. As the name suggests, most shooting guards are good shooters', 8),
(6, 'Small Forward', 'Considered to be perhaps the most versatile of the main five basketball positions,versatility is key for small forwards because of the nature of their role', 22),
(6, 'Power Forward', 'Often plays a role similar to that of the center, down in the post or low blocks. On offense, the power forward is often the most versatile scorer', 46),
(6, 'Center', 'Usually plays near the baseline, close to the basket', 16),
(15, 'Point Guard', 'Often lead their team in assists and steals. They are often quick and are able to hit shots either outside the three-point line or in the paint', 1),
(15, 'Shooting Guard', 'Often referred to as a wing because of its use in common positioning tactics. As the name suggests, most shooting guards are good shooters', 31),
(15, 'Small Forward', 'Considered to be perhaps the most versatile of the main five basketball positions,versatility is key for small forwards because of the nature of their role', 34),
(15, 'Power Forward', 'Often plays a role similar to that of the center, down in the post or low blocks. On offense, the power forward is often the most versatile scorer', 13),
(15, 'Center', 'Usually plays near the baseline, close to the basket', 24),
(13, 'Point Guard', 'Often lead their team in assists and steals. They are often quick and are able to hit shots either outside the three-point line or in the paint', 48),
(13, 'Shooting Guard', 'Often referred to as a wing because of its use in common positioning tactics. As the name suggests, most shooting guards are good shooters', 33),
(13, 'Small Forward', 'Considered to be perhaps the most versatile of the main five basketball positions,versatility is key for small forwards because of the nature of their role', 11),
(13, 'Power Forward', 'Often plays a role similar to that of the center, down in the post or low blocks. On offense, the power forward is often the most versatile scorer', 36),
(13, 'Center', 'Usually plays near the baseline, close to the basket', 45),
(9, 'Point Guard', 'Often lead their team in assists and steals. They are often quick and are able to hit shots either outside the three-point line or in the paint', 3),
(9, 'Shooting Guard', 'Often referred to as a wing because of its use in common positioning tactics. As the name suggests, most shooting guards are good shooters', 47),
(9, 'Small Forward', 'Considered to be perhaps the most versatile of the main five basketball positions,versatility is key for small forwards because of the nature of their role', 4),
(9, 'Power Forward', 'Often plays a role similar to that of the center, down in the post or low blocks. On offense, the power forward is often the most versatile scorer', 19),
(9, 'Center', 'Usually plays near the baseline, close to the basket', 50),
(20, 'Point Guard', 'Often lead their team in assists and steals. They are often quick and are able to hit shots either outside the three-point line or in the paint', 38),
(20, 'Shooting Guard', 'Often referred to as a wing because of its use in common positioning tactics. As the name suggests, most shooting guards are good shooters', 18),
(20, 'Small Forward', 'Considered to be perhaps the most versatile of the main five basketball positions,versatility is key for small forwards because of the nature of their role', 14),
(20, 'Power Forward', 'Often plays a role similar to that of the center, down in the post or low blocks. On offense, the power forward is often the most versatile scorer', 10),
(20, 'Center', 'Usually plays near the baseline, close to the basket', 43),
(34, 'Point Guard', 'Often lead their team in assists and steals. They are often quick and are able to hit shots either outside the three-point line or in the paint', 40),
(34, 'Shooting Guard', 'Often referred to as a wing because of its use in common positioning tactics. As the name suggests, most shooting guards are good shooters', 44),
(34, 'Small Forward', 'Considered to be perhaps the most versatile of the main five basketball positions,versatility is key for small forwards because of the nature of their role', 5),
(34, 'Power Forward', 'Often plays a role similar to that of the center, down in the post or low blocks. On offense, the power forward is often the most versatile scorer', 32),
(34, 'Center', 'Usually plays near the baseline, close to the basket', 30),
(30, 'Point Guard', 'Often lead their team in assists and steals. They are often quick and are able to hit shots either outside the three-point line or in the paint', 28),
(30, 'Shooting Guard', 'Often referred to as a wing because of its use in common positioning tactics. As the name suggests, most shooting guards are good shooters', 12),
(30, 'Small Forward', 'Considered to be perhaps the most versatile of the main five basketball positions,versatility is key for small forwards because of the nature of their role', 7),
(30, 'Power Forward', 'Often plays a role similar to that of the center, down in the post or low blocks. On offense, the power forward is often the most versatile scorer', 6),
(30, 'Center', 'Usually plays near the baseline, close to the basket', 42),
(8, 'Point Guard', 'Often lead their team in assists and steals. They are often quick and are able to hit shots either outside the three-point line or in the paint', 35),
(8, 'Shooting Guard', 'Often referred to as a wing because of its use in common positioning tactics. As the name suggests, most shooting guards are good shooters', 37),
(8, 'Small Forward', 'Considered to be perhaps the most versatile of the main five basketball positions,versatility is key for small forwards because of the nature of their role', 26),
(8, 'Power Forward', 'Often plays a role similar to that of the center, down in the post or low blocks. On offense, the power forward is often the most versatile scorer', 29),
(8, 'Center', 'Usually plays near the baseline, close to the basket', 41),
(25, 'Point Guard', 'Often lead their team in assists and steals. They are often quick and are able to hit shots either outside the three-point line or in the paint', 17),
(25, 'Shooting Guard', 'Often referred to as a wing because of its use in common positioning tactics. As the name suggests, most shooting guards are good shooters', 20),
(25, 'Small Forward', 'Considered to be perhaps the most versatile of the main five basketball positions,versatility is key for small forwards because of the nature of their role', 21),
(25, 'Power Forward', 'Often plays a role similar to that of the center, down in the post or low blocks. On offense, the power forward is often the most versatile scorer', 25),
(25, 'Center', 'Usually plays near the baseline, close to the basket', 27),
(781, 'Point Guard', 'Often lead their team in assists and steals. They are often quick and are able to hit shots either outside the three-point line or in the paint', 39),
(781, 'Shooting Guard', 'Often referred to as a wing because of its use in common positioning tactics. As the name suggests, most shooting guards are good shooters', 9),
(781, 'Small Forward', 'Considered to be perhaps the most versatile of the main five basketball positions,versatility is key for small forwards because of the nature of their role', 23),
(781, 'Power Forward', 'Often plays a role similar to that of the center, down in the post or low blocks. On offense, the power forward is often the most versatile scorer', 15),
(781, 'Center', 'Usually plays near the baseline, close to the basket', 2),
(801, 'Point Guard', 'Often lead their team in assists and steals. They are often quick and are able to hit shots either outside the three-point line or in the paint', 55),
(801, 'Shooting Guard', 'Often referred to as a wing because of its use in common positioning tactics. As the name suggests, most shooting guards are good shooters', 60),
(801, 'Small Forward', 'Considered to be perhaps the most versatile of the main five basketball positions,versatility is key for small forwards because of the nature of their role', 51),
(801, 'Power Forward', 'Often plays a role similar to that of the center, down in the post or low blocks. On offense, the power forward is often the most versatile scorer', 52),
(801, 'Center', 'Usually plays near the baseline, close to the basket', 53),
(605, 'Point Guard', 'Often lead their team in assists and steals. They are often quick and are able to hit shots either outside the three-point line or in the paint', 59),
(605, 'Shooting Guard', 'Often referred to as a wing because of its use in common positioning tactics. As the name suggests, most shooting guards are good shooters', 57),
(605, 'Small Forward', 'Considered to be perhaps the most versatile of the main five basketball positions,versatility is key for small forwards because of the nature of their role', 56),
(605, 'Power Forward', 'Often plays a role similar to that of the center, down in the post or low blocks. On offense, the power forward is often the most versatile scorer', 58),
(605, 'Center', 'Usually plays near the baseline, close to the basket', 54),